
(function(){var cache={};var ctx=null,usingWebAudio=true;if(typeof AudioContext!=='undefined'){ctx=new AudioContext();}else if(typeof webkitAudioContext!=='undefined'){ctx=new webkitAudioContext();}else{usingWebAudio=false;}
if(usingWebAudio){var gainNode=(typeof ctx.createGain==='undefined')?ctx.createGainNode():ctx.createGain();gainNode.gain.value=1;gainNode.connect(ctx.destination);}
var HowlerGlobal=function(){this._volume=1;this._muted=false;this.usingWebAudio=usingWebAudio;};HowlerGlobal.prototype={volume:function(vol){var self=this;if(vol&&vol>=0&&vol<=1){self._volume=vol;if(usingWebAudio){gainNode.gain.value=vol;}
for(var key in cache){if(cache.hasOwnProperty(key)&&cache[key]._webAudio===false){for(var i=0;i<cache[key]._audioNode.length;i++){cache[key]._audioNode[i].volume=cache[key]._volume*self._volume;}}}
return self;}else{if(usingWebAudio){return gainNode.gain.value;}else{return self._volume;}}},mute:function(){var self=this;self._muted=true;if(usingWebAudio){gainNode.gain.value=0;}
for(var key in cache){if(cache.hasOwnProperty(key)&&cache[key]._webAudio===false){for(var i=0;i<cache[key]._audioNode.length;i++){cache[key]._audioNode[i].volume=0;}}}
return self;},unmute:function(){var self=this;self._muted=false;if(usingWebAudio){gainNode.gain.value=self._volume;}
for(var key in cache){if(cache.hasOwnProperty(key)&&cache[key]._webAudio===false){for(var i=0;i<cache[key]._audioNode.length;i++){cache[key]._audioNode[i].volume=cache[key]._volume*self._volume;}}}
return self;}};window.Howler=new HowlerGlobal();var audioTest=new Audio();var codecs={mp3:!!audioTest.canPlayType('audio/mpeg;').replace(/^no$/,''),ogg:!!audioTest.canPlayType('audio/ogg; codecs="vorbis"').replace(/^no$/,''),wav:!!audioTest.canPlayType('audio/wav; codecs="1"').replace(/^no$/,''),m4a:!!(audioTest.canPlayType('audio/x-m4a;')||audioTest.canPlayType('audio/aac;')).replace(/^no$/,''),webm:!!audioTest.canPlayType('audio/webm; codecs="vorbis"').replace(/^no$/,'')};audioTest=null;var Howl=window.Howl=function(o){var self=this;self._autoplay=o.autoplay||false;self._buffer=o.buffer||false;self._duration=o.duration||0;self._loop=o.loop||false;self._loaded=false;self._sprite=o.sprite||{};self._src=o.src||'';self._pos=o.pos||0;self._volume=o.volume||1;self._urls=o.urls||[];self._onload=[o.onload||function(){}];self._onend=[o.onend||function(){}];self._onpause=[o.onpause||function(){}];self._onplay=[o.onplay||function(){}];self._onendTimer=[];self._webAudio=usingWebAudio&&!self._buffer;if(!self._webAudio){self._audioNode=[];}else{self._gainNode=(typeof ctx.createGain==='undefined')?ctx.createGainNode():ctx.createGain();self._gainNode.gain.value=self._volume;self._gainNode.connect(gainNode);}
self.load();};Howl.prototype={load:function(){var self=this,url=null;for(var i=0;i<self._urls.length;i++){var ext=self._urls[i].toLowerCase().match(/.+\.([^?]+)(\?|$)/),canPlay=false;ext=(ext&&ext.length>=2)?ext[1]:self._urls[i].toLowerCase().match(/data\:audio\/([^?]+);/)[1];switch(ext){case'mp3':canPlay=codecs.mp3;break;case'ogg':canPlay=codecs.ogg;break;case'wav':canPlay=codecs.wav;break;case'm4a':canPlay=codecs.m4a;break;case'weba':canPlay=codecs.webm;break;}
if(canPlay===true){url=self._urls[i];break;}}
if(!url){return;}
self._src=url;if(self._webAudio){loadBuffer(self,url);}else{var newNode=new Audio();self._audioNode.push(newNode);newNode.src=url;newNode.preload='auto';newNode.volume=(Howler._muted)?0:self._volume*Howler.volume();cache[url]=self;var listener=function(){self._duration=newNode.duration;self._loaded=true;self.on('load');if(self._autoplay){self.play();}
newNode.removeEventListener('canplaythrough',listener,false);};newNode.addEventListener('canplaythrough',listener,false);newNode.load();}
return self;},urls:function(urls){var self=this;if(urls){self._urls=urls;self.stop();self.load();return self;}else{return self._urls;}},play:function(sprite){var self=this;if(!self._loaded){self.on('load',function(){self.play(sprite);});return self;}
if(sprite&&!self._sprite[sprite]){return self;}
var pos=(sprite)?self._sprite[sprite][0]/1000:self._pos,duration=(sprite)?self._sprite[sprite][1]/1000:self._duration-pos;var soundId=Math.round(Date.now()*Math.random())+'',timerId;(function(){var data={id:soundId,sprite:sprite};timerId=setTimeout(function(){if(self._loop){self.stop().play(sprite);}
if(!self._webAudio&&sprite){self.pause(data.id,data.timer);}
self.on('end');},duration*1000);self._onendTimer.push(timerId);data.timer=self._onendTimer[self._onendTimer.length-1];})();if(self._webAudio){refreshBuffer(self);self._playStart=ctx.currentTime;if(typeof self.bufferSource.start==='undefined'){self.bufferSource.noteGrainOn(0,pos,duration);}else{self.bufferSource.start(0,pos,duration);}}else{self._inactiveNode(function(node){if(node.readyState===4){node.id=soundId;node.currentTime=pos;node.play();}else{self._clearEndTimer(timerId);(function(){var sound=self,playSprite=sprite,newNode=node;var listener=function(){sound.play(playSprite);newNode.removeEventListener('canplaythrough',listener,false);};newNode.addEventListener('canplaythrough',listener,false);})();return self;}});}
self.on('play');return self;},pause:function(id,timerId){var self=this;if(!self._loaded){self.on('load',function(){self.pause(id);});return self;}
self._clearEndTimer(timerId);if(self._webAudio){if(!self.bufferSource){return self;}
self._pos+=ctx.currentTime-self._playStart;self.bufferSource.noteOff(0);}else{var activeNode=(id)?self._nodeById(id):self._activeNode();if(activeNode){self._pos=activeNode.currentTime;activeNode.pause();}}
self.on('pause');return self;},stop:function(){var self=this;self._pos=0;if(!self._loaded){self.on('load',function(){self.stop();});return self;}
self._clearEndTimer(0);if(self._webAudio){if(!self.bufferSource){return self;}
if(typeof self.bufferSource.stop==='undefined'){self.bufferSource.noteOff(0);}else{self.bufferSource.stop(0);}}else{var activeNode=self._activeNode();if(activeNode){activeNode.pause();activeNode.currentTime=0;}}
return self;},mute:function(){var self=this;if(!self._loaded){self.on('load',function(){self.mute();});return self;}
if(self._webAudio){self._gainNode.gain.value=0;}else{var activeNode=self._activeNode();if(activeNode){activeNode.volume=0;}}
return self;},unmute:function(){var self=this;if(!self._loaded){self.on('load',function(){self.unmute();});return self;}
if(self._webAudio){self._gainNode.gain.value=self._volume;}else{var activeNode=self._activeNode();if(activeNode){activeNode.volume=self._volume;}}
return self;},volume:function(vol){var self=this;if(!self._loaded){self.on('load',function(){self.volume(vol);});return self;}
if(vol>=0&&vol<=1){self._volume=vol;if(self._webAudio){self._gainNode.gain.value=vol;}else{var activeNode=self._activeNode();if(activeNode){activeNode.volume=vol*Howler.volume();}}
return self;}else{return self._volume;}},loop:function(loop){var self=this;if(typeof loop==='boolean'){self._loop=loop;return self;}else{return self._loop;}},sprite:function(sprite){var self=this;if(typeof sprite==='object'){self._sprite=sprite;return self;}else{return self._sprite;}},pos:function(pos){var self=this;if(!self._loaded){self.on('load',function(){self.pos(pos);});return self;}
if(self._webAudio){if(pos>=0){self._pos=pos;self.pause().play();return self;}else{return self._pos+(ctx.currentTime-self._playStart);}}else{var activeNode=self._activeNode();if(!activeNode){return self;}
if(pos>=0){activeNode.currentTime=pos;return self;}else{return activeNode.currentTime;}}},fadeIn:function(to,len,callback){var self=this,dist=to,iterations=dist/0.01,hold=len/iterations;if(!self._loaded){self.on('load',function(){self.fadeIn(to,len,callback);});return self;}
self.volume(0).play();for(var i=1;i<=iterations;i++){(function(){var vol=Math.round(1000*(self._volume+0.01*i))/1000,toVol=to;setTimeout(function(){self.volume(vol);if(vol===toVol){if(callback)callback();}},hold*i);})();}
return self;},fadeOut:function(to,len,callback){var self=this,dist=self._volume-to,iterations=dist/0.01,hold=len/iterations;if(!self._loaded){self.on('load',function(){self.fadeOut(to,len,callback);});return self;}
for(var i=1;i<=iterations;i++){(function(){var vol=Math.round(1000*(self._volume-0.01*i))/1000,toVol=to;setTimeout(function(){self.volume(vol);if(vol===toVol){if(callback)callback();self.pause();}},hold*i);})();}
return self;},_nodeById:function(id){var self=this,node=null;for(var i=0;i<self._audioNode.length;i++){if(self._audioNode[i].id===id){node=self._audioNode[i];break;}}
return node;},_activeNode:function(){var self=this,node=null;for(var i=0;i<self._audioNode.length;i++){if(!self._audioNode[i].paused){node=self._audioNode[i];break;}}
self._drainPool();return node;},_inactiveNode:function(callback){var self=this,node=null;for(var i=0;i<self._audioNode.length;i++){if(self._audioNode[i].paused&&self._audioNode[i].readyState===4){callback(self._audioNode[i]);node=true;break;}}
self._drainPool();if(node){return;}
self.load();var newNode=self._audioNode[self._audioNode.length-1];newNode.addEventListener('loadedmetadata',function(){callback(newNode);});},_drainPool:function(){var self=this,inactive=0,i;for(i=0;i<self._audioNode.length;i++){if(self._audioNode[i].paused){inactive++;}}
for(i=0;i<self._audioNode.length;i++){if(inactive<=5){break;}
if(self._audioNode[i].paused){inactive--;self._audioNode.splice(i,1);}}},_clearEndTimer:function(timerId){var self=this,timer=self._onendTimer.indexOf(timerId);timer=timer>=0?timer:0;if(self._onendTimer[timer]){clearTimeout(self._onendTimer[timer]);self._onendTimer.splice(timer,1);}},on:function(event,fn){var self=this,events=self['_on'+event];if(fn){events.push(fn);}else{for(var i=0;i<events.length;i++){events[i].call();}}
return self;},off:function(event,fn){var self=this,events=self['_on'+event],fnString=fn.toString();for(var i=0;i<events.length;i++){if(fnString===events[i].toString()){events.splice(i,1);break;}}
return self;}};if(usingWebAudio){var loadBuffer=function(obj,url){if(url in cache){obj._duration=cache[url].duration;loadSound(obj);}else{var xhr=new XMLHttpRequest();xhr.open('GET',url,true);xhr.responseType='arraybuffer';xhr.onload=function(){ctx.decodeAudioData(xhr.response,function(buffer){if(buffer){cache[url]=buffer;loadSound(obj,buffer);}});};xhr.send();}};var loadSound=function(obj,buffer){obj._duration=(buffer)?buffer.duration:obj._duration;obj._loaded=true;obj.on('load');if(obj._autoplay){obj.play();}};var refreshBuffer=function(obj){obj.bufferSource=ctx.createBufferSource();obj.bufferSource.buffer=cache[obj._src];obj.bufferSource.connect(obj._gainNode);obj.bufferSource.loop=obj._loop;};}})();