
﻿
var start_tongue_med_segment=46;var tong_med_size=34;var tongue_offset={x:193,y:16};var tongue_tilting_angle=25;var max_tongue_frames=3;var max_tongue_size=700;var max_eye_sprites=8;var max_tail_sprites=3;var inactive_time=5;PlayerClass=EntityClass.extend({id:"Player",points:0,volatile_points:0,volatile_points_timer:0,health:255,dead:false,dizzy:false,walkSpeed:20,zindex:50,currSpriteName:null,health_timer:0,last_fire_timer:0,local_player_canvas:null,local_player_context:null,frame:1,total_frames:3,direction:true,moving:false,direct_eyes:false,last_eye_changed:0,current_eye:1,last_tail_changed:0,current_tail:0,alpha:0,yellow_filter:{canvas:null,context:null,intensity:0.0},red_filter:{canvas:null,context:null,intensity:0.0},dead_altitud:0,miss_in_da_face:false,tongue_frame:0,tong_pos:{x:0,y:0},tong_fire_pos:{x:0,y:0},tong_offset:{x:tongue_offset.x,y:tongue_offset.y},tong_distance:0,angle:0,t_start:"kami-tongue-001.png",t_med:"kami-tongue-002.png",t_end:"kami-tongue-003.png",entityDef:null,physBody:null,init:function(x,y){this.parent(x,y);this.dead_altitud=y-10;var startPos={x:x,y:y};this.entityDef={id:"Player",type:'static',x:startPos.x,y:startPos.y,halfHeight:80,halfWidth:200,angle:0,userData:{"id":"Player","ent":this}};this.physBody=null;this.local_player_canvas=document.createElement("canvas");this.local_player_canvas.width=canvas.width;this.local_player_canvas.height=canvas.height;this.local_player_context=this.local_player_canvas.getContext('2d');},update:function(){if(!this.dead){var now=(new Date()).getTime();var move_dir={x:0,y:0};if((gInput.actions['move-left'])&&(this.pos.x>100)){move_dir.x-=this.walkSpeed;this.moving=true;console.log("Muevo Izq");}
if((gInput.actions['move-right'])&&(this.pos.x<canvas.width-150)){if(this.moving){this.current_eye=Math.floor(Math.random()*(max_eye_sprites+1));this.current_tail=Math.floor(Math.random()*(max_tail_sprites+1));if(!this.dizzy&&(this.current_tail%5==0)){launchBurpSound();this.dizzy=true;}
this.moving=this.current_tail%5==0;}else{this.dizzy=false;this.moving=true;}
move_dir.x+=this.walkSpeed;console.log("Muevo Derch");}
this.pos.x+=move_dir.x;if((now/10)-this.last_eye_changed>100){this.last_eye_changed=now/10;this.current_eye=Math.floor(Math.random()*(max_eye_sprites+1));}
if(this.alpha!=0){this.current_tail=0;}else{if(this.current_tail==2){this.last_tail_changed-=20;}
if((now/10)-this.last_tail_changed>150){this.last_tail_changed=now/10;this.current_tail=Math.floor(Math.random()*(max_tail_sprites+1));}}
var angle_calculated=false;if(gInput.actions['fire-mouse']){this.tong_fire_pos.x=gInput.mouse.x;this.tong_fire_pos.y=gInput.mouse.y;this.last_fire_timer=now/1000;}
if((gInput.actions['fire-mouse']||(this.tongue_frame!=0))&&!angle_calculated){this.calculatePointerAngle(false);angle_calculated=true;}
if(gInput.actions['fire-mouse']){gInput.actions['fire-mouse']=false;this.tongue_frame=1;this.current_tail=2;if((this.angle<-1.9078242687063418)||(this.angle>0.065)||this.tong_distance<100){this.miss_in_da_face=true;launchSlapSound();}else{this.miss_in_da_face=false;launchTongueSound();}
if(!gamer_active&&!play_game_intro){if(sound_atmos_active&&!game_music_active){gamer_active=true;gEngine.activateMusic();}}}else if((this.last_fire_timer!=0)&&gamer_active&&((now/1000)-this.last_fire_timer>inactive_time)){if(game_music_active&&!sound_atmos_active){gamer_active=false;gEngine.activateAtmosMusic();}}
if(this.direct_eyes){this.direct_eyes=false;if(!angle_calculated){this.calculatePointerAngle(true);}
angle_calculated=true;var degrees=-(this.angle*(180/Math.PI))%360;if(degrees>=-15&&degrees<30){if(this.tong_distance>=max_tongue_size*0.8){this.current_eye=5;}else{this.current_eye=1;}}else if(degrees>=30&&degrees<60){this.current_eye=2;}else if(degrees>=60&&degrees<100){this.current_eye=4;}}
if(this.health_timer!=0){if((now-this.health_timer>=200)&&(!this.dead)&&(!victory)){this.health-=1;if(this.points>30){this.health-=Math.floor(this.points/30);}
this.health_timer=now;}
if(now-this.volatile_points_timer>=4000){if(this.volatile_points>0){if((this.health>150)||(this.volatile_points==1)){this.volatile_points--;}else if(this.volatile_points>1){this.volatile_points-=2;}}
this.volatile_points_timer=now;}}else if(!play_game_intro&&!game_instructions){this.health_timer=(new Date()).getTime();}
this.red_filter.intensity=this.volatile_points/10;if(this.health<=150){this.alpha=(this.health+20)/255;}else{this.alpha=1.0;}
if(this.size.width==0&&this.size.height==0){var sprite=getSprite(this.spritename+'1.png');if((typeof sprite!=='undefined')&&(sprite!=null)&&(sprite.w!=null)&&(sprite.h!=null)){this.size.width=sprite.w;this.size.height=sprite.h;}}
if(this.health<=70){this.dead=true;game_music.fadeOut(0.0,3000,null);sound_atmos.fadeOut(0.0,3000,null);kami_death.play("death").fadeIn(0.5,5000);this.tongue_frame=1;this.angle=0.1;}}else{this.dead_altitud-=(1.8+(this.angle*2));if(this.angle<1){this.angle+=0.008;}
if(this.dead_altitud<=10){gEngine.endGame();}}},calculatePointerAngle:function(use_current_mouse_position){this.tong_pos.x=this.pos.x+this.tong_offset.x;this.tong_pos.y=this.pos.y+this.tong_offset.y;var tong_size_x=this.tong_fire_pos.x-this.tong_pos.x;var tong_size_y=this.tong_fire_pos.y-this.tong_pos.y;if(use_current_mouse_position){tong_size_x=gInput.mouse.x-this.tong_pos.x;tong_size_y=gInput.mouse.y-this.tong_pos.y;}
this.tong_distance=Math.sqrt((tong_size_x*tong_size_x)+(tong_size_y*tong_size_y));if(this.tong_distance>max_tongue_size){this.tong_distance=max_tongue_size;if(gInput.actions['fire-mouse']){launchSound('tongmax');}}
var angle_tip_tongue_offset=Math.atan2(-tongue_tilting_angle,this.tong_distance);this.angle=-Math.atan2(-tong_size_y,tong_size_x)
if(this.tong_distance==max_tongue_size){this.tong_fire_pos.x=(Math.cos(this.angle)*max_tongue_size)+this.tong_pos.x;this.tong_fire_pos.y=(Math.sin(this.angle)*max_tongue_size)+this.tong_pos.y;}
this.angle+=angle_tip_tongue_offset;},draw:function(){if(this.spritename){player_context.globalAlpha=this.alpha;this.local_player_context.clearRect(0,0,this.local_player_canvas.width,this.local_player_canvas.height);if(!this.dead){if(this.moving){if(this.direction){this.frame++;}else{this.frame--;}
if((this.frame==1)||(this.frame==this.total_frames)){this.direction=!this.direction;}
this.moving=false;}
var real_spritename=this.spritename+this.frame+'.png';drawSprite(real_spritename,this.pos.x,this.pos.y,null,this.local_player_context);if(this.miss_in_da_face&&(this.tongue_frame!=0)){this.local_player_context.clearRect(this.pos.x+123,this.pos.y-25,80,62);this.local_player_context.clearRect(this.pos.x+140,this.pos.y+24,80,20);this.local_player_context.clearRect(this.pos.x+112,this.pos.y-96,48,48);drawSprite('kami-head-slap.png',this.pos.x+163,this.pos.y-25,null,this.local_player_context);}else{if(this.current_eye!=0){drawSprite('kami-eye-00'+this.current_eye+'.png',this.pos.x+162,this.pos.y-37,null,this.local_player_context);}}
if(this.current_tail!=0){this.local_player_context.clearRect(this.pos.x-(this.size.width/2)+60,this.pos.y+5,70,40);this.local_player_context.clearRect(this.pos.x-(this.size.width/2),this.pos.y-30,120,100);drawSprite('kami-tail-00'+this.current_tail+'.png',this.pos.x-132,this.pos.y+33,null,this.local_player_context);}
this.change_color(real_spritename,this.pos.x,this.pos.y,this.angle,this.local_player_context);if(this.tongue_frame!=0){if(!this.miss_in_da_face){drawSprite(this.t_start,this.tong_pos.x,this.tong_pos.y,this.angle,this.local_player_context);var current_tong_pos_x=this.tong_pos.x;var current_tong_pos_y=this.tong_pos.y;var distance=this.tong_distance/(max_tongue_frames-this.tongue_frame);if(this.tong_distance<200){distance=this.tong_distance}
while(distance-start_tongue_med_segment>tong_med_size){drawSprite(this.t_med,current_tong_pos_x,current_tong_pos_y,this.angle,this.local_player_context);distance-=tong_med_size;current_tong_pos_x+=Math.cos(this.angle)*tong_med_size;current_tong_pos_y+=Math.sin(this.angle)*tong_med_size;}
current_tong_pos_x-=Math.cos(this.angle)*(tong_med_size*2);current_tong_pos_y-=Math.sin(this.angle)*(tong_med_size*2);current_tong_pos_x+=Math.cos(this.angle)*(distance-start_tongue_med_segment);current_tong_pos_y+=Math.sin(this.angle)*(distance-start_tongue_med_segment);drawSprite(this.t_end,current_tong_pos_x,current_tong_pos_y,this.angle,this.local_player_context);this.tongue_frame=(this.tongue_frame+1)%(max_tongue_frames);}else{this.tongue_frame=(this.tongue_frame+1)%(max_tongue_frames+(max_tongue_frames/2));}}}else{player_context.globalAlpha=1.0;this.local_player_context.globalAlpha=0.27;if(this.dead_altitud<this.pos.y-30){this.tongue_frame=2;var real_spritename=this.spritename+this.frame+'.png';drawSprite(real_spritename,this.pos.x,this.dead_altitud,this.angle,this.local_player_context);this.change_color(real_spritename,this.pos.x,this.dead_altitud,this.angle,this.local_player_context);}
this.local_player_context.globalAlpha=1.0;drawSprite('kami-dead-00'+this.tongue_frame+'.png',this.pos.x,this.pos.y,null,this.local_player_context);}
if(!game_instructions&&!background_loaded){player_context.globalCompositeOperation='copy';}
player_context.drawImage(this.local_player_canvas,0,0,canvas.width,canvas.height,0,0,canvas.width,canvas.height);}},change_color:function(spritename,posX,posY,angle,draw_context){if(this.red_filter.intensity>0){if(this.red_filter.canvas==null){this.red_filter.canvas=document.createElement("canvas");this.red_filter.canvas.width=canvas.width;this.red_filter.canvas.height=canvas.height;this.red_filter.context=this.red_filter.canvas.getContext('2d');this.red_filter.context.fillStyle='rgba(255, 0, 0, 0.55)';this.red_filter.context.fillRect(0,0,canvas.width,canvas.height);}
var saved_alpha=draw_context.globalAlpha;draw_context.globalAlpha=this.red_filter.intensity;draw_context.globalCompositeOperation='source-atop';draw_context.drawImage(this.red_filter.canvas,0,0,canvas.width,canvas.height,0,0,canvas.width,canvas.height);draw_context.globalCompositeOperation='source-over';draw_context.globalAlpha=saved_alpha;}
if(this.yellow_filter.intensity>0){if(this.yellow_filter.canvas==null){this.yellow_filter.canvas=document.createElement("canvas");this.yellow_filter.canvas.width=canvas.width;this.yellow_filter.canvas.height=canvas.height;this.yellow_filter.context=this.yellow_filter.canvas.getContext('2d');this.yellow_filter.context.fillStyle='rgba(225, 255, 0, 0.55)';this.yellow_filter.context.fillRect(0,0,canvas.width,canvas.height);}
var saved_alpha=draw_context.globalAlpha;draw_context.globalAlpha=this.yellow_filter.intensity;draw_context.globalCompositeOperation='source-atop';draw_context.drawImage(this.yellow_filter.canvas,0,0,canvas.width,canvas.height,0,0,canvas.width,canvas.height);draw_context.globalCompositeOperation='source-over';draw_context.globalAlpha=saved_alpha;}}});gEngine.factory['Player']=PlayerClass;var gamer_active=false;