
﻿
var start_tongue_med_segment=46;var tong_med_size=34;var tongue_offset={x:193,y:16};var tongue_tilting_angle=25;var max_tongue_frames=3;var max_tongue_size=700;var max_eye_sprites=8;var max_tail_sprites=3;var inactive_time=5;PlayerClass=EntityClass.extend({id:"Player",points:0,volatile_points:0,volatile_points_timer:0,health:255,dead:false,dizzy:false,walkSpeed:20,zindex:50,currSpriteName:null,health_timer:0,last_fire_timer:0,frame:1,total_frames:3,direction:true,moving:false,direct_eyes:false,last_eye_changed:0,current_eye:1,last_tail_changed:0,current_tail:0,color_variation:{red:0,green:0,blue:0,alpha:0},special_color:{red:0,green:0,blue:0},dead_altitud:0,miss_in_da_face:false,tongue_frame:0,tong_pos:{x:0,y:0},tong_fire_pos:{x:0,y:0},tong_offset:{x:tongue_offset.x,y:tongue_offset.y},tong_distance:0,angle:0,t_start:"kami-tongue-001.png",t_med:"kami-tongue-002.png",t_end:"kami-tongue-003.png",entityDef:null,physBody:null,init:function(x,y){this.parent(x,y);this.dead_altitud=y-10;var startPos={x:x,y:y};this.entityDef={id:"Player",type:'static',x:startPos.x,y:startPos.y,halfHeight:80,halfWidth:200,angle:0,userData:{"id":"Player","ent":this}};this.physBody=null;},update:function(){if(!this.dead){var now=(new Date()).getTime();var move_dir={x:0,y:0};if((gInput.actions['move-left'])&&(this.pos.x>100)){move_dir.x-=this.walkSpeed;this.moving=true;console.log("Muevo Izq");}
if((gInput.actions['move-right'])&&(this.pos.x<canvas.width-150)){if(this.moving){this.current_eye=Math.floor(Math.random()*(max_eye_sprites+1));this.current_tail=Math.floor(Math.random()*(max_tail_sprites+1));if(!this.dizzy&&(this.current_tail%5==0)){launchBurpSound();this.dizzy=true;}
this.moving=this.current_tail%5==0;}else{this.dizzy=false;this.moving=true;}
move_dir.x+=this.walkSpeed;console.log("Muevo Derch");}
this.pos.x+=move_dir.x;if((now/10)-this.last_eye_changed>100){this.last_eye_changed=now/10;this.current_eye=Math.floor(Math.random()*(max_eye_sprites+1));}
if(this.color_variation.alpha!=0){this.current_tail=0;}else{if(this.current_tail==2){this.last_tail_changed-=20;}
if((now/10)-this.last_tail_changed>150){this.last_tail_changed=now/10;this.current_tail=Math.floor(Math.random()*(max_tail_sprites+1));}}
var angle_calculated=false;if(gInput.actions['fire-mouse']){this.tong_fire_pos.x=gInput.mouse.x;this.tong_fire_pos.y=gInput.mouse.y;this.last_fire_timer=now/1000;}
if((gInput.actions['fire-mouse']||(this.tongue_frame!=0))&&!angle_calculated){this.calculatePointerAngle(false);angle_calculated=true;}
if(gInput.actions['fire-mouse']){gInput.actions['fire-mouse']=false;this.tongue_frame=1;this.current_tail=2;if((this.angle<-1.9078242687063418)||(this.angle>0.065)||this.tong_distance<100){this.miss_in_da_face=true;launchSlapSound();}else{this.miss_in_da_face=false;launchTongueSound();}
if(!gamer_active&&!play_game_intro){if(sound_atmos_active&&!game_music_active){gamer_active=true;gEngine.activateMusic();}}}else if((this.last_fire_timer!=0)&&gamer_active&&((now/1000)-this.last_fire_timer>inactive_time)){if(game_music_active&&!sound_atmos_active){gamer_active=false;gEngine.activateAtmosMusic();}}
if(this.direct_eyes){this.direct_eyes=false;if(!angle_calculated){this.calculatePointerAngle(true);}
angle_calculated=true;var degrees=-(this.angle*(180/Math.PI))%360;if(degrees>=-15&&degrees<30){if(this.tong_distance>=max_tongue_size*0.8){this.current_eye=5;}else{this.current_eye=1;}}else if(degrees>=30&&degrees<60){this.current_eye=2;}else if(degrees>=60&&degrees<100){this.current_eye=4;}}
if(this.health_timer!=0){if((now-this.health_timer>=200)&&(!this.dead)&&(!victory)){this.health-=1;if(this.points>30){this.health-=Math.floor(this.points/30);}
this.health_timer=now;}
if(now-this.volatile_points_timer>=4000){if(this.volatile_points>0){if(this.health>150){this.volatile_points--;}else{this.volatile_points-=2;}}
this.volatile_points_timer=now;}}else if(!play_game_intro&&!game_instructions){this.health_timer=(new Date()).getTime();}
this.color_variation.red=8*this.volatile_points+(255-this.health)+this.special_color.red;this.color_variation.green=-2*this.volatile_points+(255-this.health)+this.special_color.green;this.color_variation.blue=-2*this.volatile_points+(255-this.health)+this.special_color.blue;if(this.health<=150){this.color_variation.alpha=(this.health*255/150)-255;}else{this.color_variation.alpha=0;}
if(this.size.width==0&&this.size.height==0){var sprite=getSprite(this.spritename+'1.png');if((typeof sprite!=='undefined')&&(sprite!=null)&&(sprite.w!=null)&&(sprite.h!=null)){this.size.width=sprite.w;this.size.height=sprite.h;}}
if(this.health<=70){this.dead=true;game_music.fadeOut(0.0,3000,null);sound_atmos.fadeOut(0.0,3000,null);kami_death.play("death").fadeIn(0.5,5000);this.tongue_frame=1;this.angle=0.1;}}else{this.dead_altitud-=(1.8+(this.angle*2));if(this.angle<1){this.angle+=0.008;}
if(this.dead_altitud<=10){gEngine.endGame();}}},calculatePointerAngle:function(use_current_mouse_position){this.tong_pos.x=this.pos.x+this.tong_offset.x;this.tong_pos.y=this.pos.y+this.tong_offset.y;var tong_size_x=this.tong_fire_pos.x-this.tong_pos.x;var tong_size_y=this.tong_fire_pos.y-this.tong_pos.y;if(use_current_mouse_position){tong_size_x=gInput.mouse.x-this.tong_pos.x;tong_size_y=gInput.mouse.y-this.tong_pos.y;}
this.tong_distance=Math.sqrt((tong_size_x*tong_size_x)+(tong_size_y*tong_size_y));if(this.tong_distance>max_tongue_size){this.tong_distance=max_tongue_size;if(gInput.actions['fire-mouse']){launchSound('tongmax');}}
var angle_tip_tongue_offset=Math.atan2(-tongue_tilting_angle,this.tong_distance);this.angle=-Math.atan2(-tong_size_y,tong_size_x)
if(this.tong_distance==max_tongue_size){this.tong_fire_pos.x=(Math.cos(this.angle)*max_tongue_size)+this.tong_pos.x;this.tong_fire_pos.y=(Math.sin(this.angle)*max_tongue_size)+this.tong_pos.y;}
this.angle+=angle_tip_tongue_offset;},draw:function(){if(this.spritename){if(!this.dead){if(this.moving){if(this.direction){this.frame++;}else{this.frame--;}
if((this.frame==1)||(this.frame==this.total_frames)){this.direction=!this.direction;}
this.moving=false;}
var real_spritename=this.spritename+this.frame+'.png';drawSprite(real_spritename,this.pos.x,this.pos.y,null,player_context);if(this.miss_in_da_face&&(this.tongue_frame!=0)){player_context.clearRect(this.pos.x+123,this.pos.y-25,80,62);player_context.clearRect(this.pos.x+140,this.pos.y+24,80,20);player_context.clearRect(this.pos.x+112,this.pos.y-96,48,48);drawSprite('kami-head-slap.png',this.pos.x+163,this.pos.y-25,null,player_context);}else{if(this.current_eye!=0){drawSprite('kami-eye-00'+this.current_eye+'.png',this.pos.x+162,this.pos.y-37,null,player_context);}}
if(this.current_tail!=0){player_context.clearRect(this.pos.x-(this.size.width/2)+60,this.pos.y+5,70,40);player_context.clearRect(this.pos.x-(this.size.width/2),this.pos.y-30,120,100);drawSprite('kami-tail-00'+this.current_tail+'.png',this.pos.x-132,this.pos.y+33,null,player_context);}
this.change_color(real_spritename,this.pos.x,this.pos.y,this.angle,player_context);if(this.tongue_frame!=0){if(!this.miss_in_da_face){drawSprite(this.t_start,this.tong_pos.x,this.tong_pos.y,this.angle,player_context);var current_tong_pos_x=this.tong_pos.x;var current_tong_pos_y=this.tong_pos.y;var distance=this.tong_distance/(max_tongue_frames-this.tongue_frame);if(this.tong_distance<200){distance=this.tong_distance}
while(distance-start_tongue_med_segment>tong_med_size){drawSprite(this.t_med,current_tong_pos_x,current_tong_pos_y,this.angle,player_context);distance-=tong_med_size;current_tong_pos_x+=Math.cos(this.angle)*tong_med_size;current_tong_pos_y+=Math.sin(this.angle)*tong_med_size;}
current_tong_pos_x-=Math.cos(this.angle)*(tong_med_size*2);current_tong_pos_y-=Math.sin(this.angle)*(tong_med_size*2);current_tong_pos_x+=Math.cos(this.angle)*(distance-start_tongue_med_segment);current_tong_pos_y+=Math.sin(this.angle)*(distance-start_tongue_med_segment);drawSprite(this.t_end,current_tong_pos_x,current_tong_pos_y,this.angle,player_context);this.tongue_frame=(this.tongue_frame+1)%(max_tongue_frames);}else{this.tongue_frame=(this.tongue_frame+1)%(max_tongue_frames+(max_tongue_frames/2));}}}else{if(this.dead_altitud<this.pos.y-30){this.tongue_frame=2;var real_spritename=this.spritename+this.frame+'.png';drawSprite(real_spritename,this.pos.x,this.dead_altitud,this.angle,player_context);this.change_color(real_spritename,this.pos.x,this.dead_altitud,this.angle,player_context);}
drawSprite('kami-dead-00'+this.tongue_frame+'.png',this.pos.x,this.pos.y,null,player_context);}}},change_color:function(spritename,posX,posY,angle,draw_context){var offset_face=50;var sprite=getSprite(spritename);var pos={x:posX-(sprite.w/2),y:posY-(sprite.h/2)};var drawing_pos={x:pos.x,y:pos.y};var max_side=0;var imageData=null;if((typeof angle!=='undefined')&&(angle!=null)&&(angle!=0)){draw_context.translate(pos.x,pos.y);draw_context.rotate(angle);max_side=Math.max(sprite.w+offset_face,sprite.h);drawing_pos={x:posX-(max_side/2),y:posY-(max_side/2)};imageData=draw_context.getImageData(drawing_pos.x,drawing_pos.y,max_side,max_side);}else{imageData=draw_context.getImageData(drawing_pos.x,drawing_pos.y,sprite.w+offset_face,sprite.h);}
var data=imageData.data;for(var i=0;i<data.length;i+=4){if(data[i+3]==0){continue;}
data[i]=this.color_variation.red+data[i];data[i+1]=this.color_variation.green+data[i+1];data[i+2]=this.color_variation.blue+data[i+2];if(this.color_variation.alpha!=0){data[i+3]=this.color_variation.alpha+data[i+3];}}
var offset_tail=0;if(this.current_tail!=0){offset_tail={x:100,y:5};var tailImageData=draw_context.getImageData(pos.x-offset_tail.x,pos.y-offset_tail.y,sprite.w/3,sprite.h);data=tailImageData.data;for(var i=0;i<data.length;i+=4){if(data[i+3]==0){continue;}
data[i]=this.color_variation.red+data[i];data[i+1]=this.color_variation.green+data[i+1];data[i+2]=this.color_variation.blue+data[i+2];if(this.color_variation.alpha!=0){data[i+3]=this.color_variation.alpha+data[i+3];}}
draw_context.putImageData(tailImageData,pos.x-offset_tail.x,pos.y-offset_tail.y);}
draw_context.putImageData(imageData,drawing_pos.x,drawing_pos.y);if((typeof angle!=='undefined')&&(angle!=null)&&(angle!=0)){draw_context.rotate(-angle);draw_context.translate(-pos.x,-pos.y);}}});gEngine.factory['Player']=PlayerClass;var gamer_active=false;